# Generated by Django 5.2 on 2026-02-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название артефакта, отображаемое в интерфейсе.', max_length=255, verbose_name='Артефакт')),
                ('uid', models.CharField(help_text='Уникальный строковый идентификатор артефакта.', max_length=100, unique=True, verbose_name='Идентификатор')),
                ('latitude', models.FloatField(help_text='Географическая широта: от -90 до 90 градусов.', verbose_name='Широта')),
                ('longitude', models.FloatField(help_text='Географическая долгота: от -180 до 180 градусов.', verbose_name='Долгота')),
                ('picture', models.URLField(help_text='Прямая ссылка на изображение артефакта.', verbose_name='Изображение')),
                ('value', models.IntegerField(blank=True, default=None, help_text='Числовая ценность артефакта, например, в игровых очках.', null=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Артефакт',
                'verbose_name_plural': 'Артефакты',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='artifacts_c_latitud_dd350a_idx')],
            },
        ),
    ]
