# Generated by Django 5.2 on 2026-02-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Географическая широта: от -90 до 90 градусов.', null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Географическая долгота: от -180 до 180 градусов.', null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='name',
            field=models.CharField(blank=True, help_text='Название артефакта, отображаемое в интерфейсе.', max_length=255, null=True, verbose_name='Артефакт'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='picture',
            field=models.URLField(blank=True, help_text='Прямая ссылка на изображение артефакта.', null=True, verbose_name='Изображение'),
        ),
    ]
