# Generated by Django 5.2 on 2026-02-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_alter_collectibleitem_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='latitude',
            field=models.FloatField(default=0.0, help_text='Географическая широта: от -90 до 90 градусов.', verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='longitude',
            field=models.FloatField(default=0.0, help_text='Географическая долгота: от -180 до 180 градусов.', verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='name',
            field=models.CharField(default='', help_text='Название артефакта, отображаемое в интерфейсе.', max_length=255, verbose_name='Артефакт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='picture',
            field=models.URLField(default='https://google.com', help_text='Прямая ссылка на изображение артефакта.', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='value',
            field=models.IntegerField(default=0, help_text='Числовая ценность артефакта, например, в игровых очках.', verbose_name='Значение'),
            preserve_default=False,
        ),
    ]
