# Generated by Django 5.2 on 2026-02-17 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_alter_collectibleitem_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='items',
            field=models.ManyToManyField(help_text='Список собранных предметов.', related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Награды'),
        ),
    ]
