# Generated by Django 5.2 on 2026-02-07 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании записи.', verbose_name='Дата начала забега')),
                ('comment', models.TextField(blank=True, help_text='Дополнительная информация о забеге: состояние, погода, настроение и т.д.', null=True, verbose_name='Комментарий')),
                ('athlete', models.ForeignKey(help_text='Пользователь, который совершил забег.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Атлет')),
            ],
            options={
                'verbose_name': 'Забег',
                'verbose_name_plural': 'Забеги',
                'ordering': ['-created_at'],
            },
        ),
    ]
