# Generated by Django 5.2 on 2026-02-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Забег инициализирован'), ('in_progress', 'Забег начат'), ('finished', 'Забег закончен')], db_index=True, default='init', help_text='Текущий статус забега: инициализация, в процессе, завершён.', max_length=11, verbose_name='Статус забега'),
        ),
    ]
