# Generated by Django 5.2 on 2026-02-11 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_alter_run_athlete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.CharField(help_text='Описание целей спортсмена.', max_length=255, verbose_name='Цели')),
                ('weight', models.IntegerField(help_text='Текущий вес спортсмена в килограммах.', verbose_name='Вес')),
                ('athlete', models.OneToOneField(help_text='Связанный пользователь, представляющий атлета.', on_delete=django.db.models.deletion.CASCADE, related_name='athlete_info', to=settings.AUTH_USER_MODEL, verbose_name='Атлет')),
            ],
            options={
                'verbose_name': 'Информация о спортсмене',
                'verbose_name_plural': 'Информация о спортсменах',
            },
        ),
    ]
