# Generated by Django 5.2 on 2026-02-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0004_athleteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.CharField(blank=True, default=None, help_text='Описание целей спортсмена.', max_length=255, null=True, verbose_name='Цели'),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.IntegerField(blank=True, default=None, help_text='Текущий вес спортсмена в килограммах.', null=True, verbose_name='Вес'),
        ),
    ]
