# Generated by Django 5.2 on 2026-02-12 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0005_alter_athleteinfo_goals_alter_athleteinfo_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Введите полное название испытания.', max_length=255, verbose_name='Испытание')),
                ('athlete', models.ForeignKey(help_text='Выберите пользователя, который проходит это испытание.', on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL, verbose_name='Атлет')),
            ],
            options={
                'verbose_name': 'Испытание',
                'verbose_name_plural': 'Испытания',
            },
        ),
    ]
