# Generated by Django 5.2 on 2026-02-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0007_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.FloatField(blank=True, default=0.0, help_text='Расстояние, которое пробежал атлет', verbose_name='Дистанция'),
        ),
    ]
