# Generated by Django 5.2 on 2026-02-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_run_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(blank=True, help_text='Точная временная метка позиции, переданная трекером.', null=True, verbose_name='Время фиксации'),
        ),
    ]
