# Generated by Django 5.2 on 2026-02-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_position_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(blank=True, default=0, help_text='Время, затраченное на забег в секундах', verbose_name='Время забега'),
        ),
    ]
