# Generated by Django 5.2 on 2026-02-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_run_run_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0.0, help_text='Скорость в метрах в секунду', verbose_name='Скорость'),
        ),
    ]
