# Generated by Django 5.2 on 2026-02-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_position_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.FloatField(default=0.0, help_text='Суммарное расстояние от начала забега до этой точки (в километрах).', verbose_name='Расстояние'),
        ),
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0.0, help_text='Скорость в метрах в секунду.', verbose_name='Скорость'),
        ),
    ]
