# Generated by Django 5.2 on 2026-02-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0012_position_distance_alter_position_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(default=0.0, help_text='Средняя скорость от всех позиций.', verbose_name='Скорость'),
        ),
    ]
