# Generated by Django 5.2 on 2026-03-01 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='rating',
            field=models.IntegerField(blank=True, default=None, help_text='Оценка тренера от 1 до 5. Не заполняется по умолчанию.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рэйтинг'),
        ),
    ]
